### PR TITLE
isDevMode that was set in global scope should be respected

### PR DESCRIPTION
**Pull request by Atry**

### CODE REVIEW

**Comment by Atry** [comment]
At the moment, if I set `isDevMode in ThisBuild := true`, sbt-web-scalajs will ignore the setting.

**Comment by vmunier** [comment]
Hi Atry,

> if I set isDevMode in ThisBuild := true, sbt-web-scalajs will ignore the setting

It's intentional, you need to use `scalaJSPipeline` as a scope if you want to set `isDevMode` from sbt-web-scalajs, e.g.: `isDevMode in scalaJSPipeline := true`

It allows users to define their own `isDevMode` for a different purpose. sbt-web-scalajs will only look at `isDevMode in scalaJSPipeline` and not `isDevMode`.

**Comment by Atry** [comment]
I totally agree that sbt-web-scalajs should only look at `isDevMode in scalaJSPipeline`.
However, sbt-web-scalajs should respect the value of previously assigned `isDevMode in scalaJSPipeline` by default, which is the behavior of this PR.

**Comment by vmunier** [comment]
I am not sure I understand the issue.

If I have a project that uses sbt-web-scalajs and I set `isDevMode in scalaJSPipeline := true` in my build.sbt, then the plugin will use the new value `true`.

Could you please give me an example of the problem / what you would expect?

**Comment by Atry** [comment]
This PR does not change the behavior when you set `isDevMode in scalaJSPipeline := true` in `build.sbt`, because the value is set after this plugin.

This PR changes the behaviors in these cases:
 * There are three projects. The root project aggregates a sbt-web project and a Scala.js project. Set `isDevMode in scalaJSPipeline in myWebProject := true` in `<root>/build.sbt`, and `enablePlugins(SbtWebScalaJS)` in `myWebProject/build.sbt`.
 * Set `isDevMode in ThisBuild := true` in `myWebProject/build.sbt`.

**Comment by vmunier** [comment]
Closing because `isDevMode` does not exist anymore. sbt-web-scalajs `v1.1.0` now relies on `scalaJSStage` to know whether `fastOptJS` or `fullOptJS` should be run.

**Pull request closed without merging**
